config/routes.rb
require 'csv'

Rails.application.routes.draw do
  resources :predict_data
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #objects に限り、post で import 処理を許可する
  resources 'predict_data', only: :index do
    collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/predict_datum.rb
class PredictDatum < ApplicationRecord
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
    
          obj = new
          obj.attributes = row.to_hash.slice(*updatable_attributes)
    
          obj.save!
        end
      end
    
    def self.updatable_attributes
        ["image_name", "beautiful_sky", "not_beautiful_sky", "other"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with :name => "gs", :password => "kodama" if Rails.env == "production"
end

app/controllers/predict_data_controller.rb
class PredictDataController < ApplicationController
  before_action :set_predict_datum, only: [:show, :edit, :update, :destroy]

  # GET /predict_data
  # GET /predict_data.json
  def index
    # params[:sort] = params[:sort] + " DESC"
    @predict_data = PredictDatum.page(params[:page]).per(100).order(params[:sort])
  end

  # GET /predict_data/1
  # GET /predict_data/1.json
  def show
  end

  # GET /predict_data/new
  def new
    @predict_datum = PredictDatum.new
  end

  # GET /predict_data/1/edit
  def edit
  end

  # POST /predict_data
  # POST /predict_data.json
  def create
    @predict_datum = PredictDatum.new(predict_datum_params)

    respond_to do |format|
      if @predict_datum.save
        format.html { redirect_to @predict_datum, notice: 'Predict datum was successfully created.' }
        format.json { render :show, status: :created, location: @predict_datum }
      else
        format.html { render :new }
        format.json { render json: @predict_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predict_data/1
  # PATCH/PUT /predict_data/1.json
  def update
    respond_to do |format|
      if @predict_datum.update(predict_datum_params)
        format.html { redirect_to @predict_datum, notice: 'Predict datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @predict_datum }
      else
        format.html { render :edit }
        format.json { render json: @predict_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predict_data/1
  # DELETE /predict_data/1.json
  def destroy
    @predict_datum.destroy
    respond_to do |format|
      format.html { redirect_to predict_data_url, notice: 'Predict datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    PredictDatum.import(params[:file])
    redirect_to "/predict_data"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_predict_datum
      @predict_datum = PredictDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def predict_datum_params
      params.require(:predict_datum).permit(:image_name, :beautiful_sky, :not_beautiful_sky, :other)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/predict_data_helper.rb
module PredictDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RankingTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/predict_data/_form.html.erb
<%= form_with(model: predict_datum, local: true) do |form| %>
  <% if predict_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(predict_datum.errors.count, "error") %> prohibited this predict_datum from being saved:</h2>

      <ul>
      <% predict_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image_name %>
    <%= form.text_field :image_name %>
  </div>

  <div class="field">
    <%= form.label :beautiful_sky %>
    <%= form.text_field :beautiful_sky %>
  </div>

  <div class="field">
    <%= form.label :not_beautiful_sky %>
    <%= form.text_field :not_beautiful_sky %>
  </div>

  <div class="field">
    <%= form.label :other %>
    <%= form.text_field :other %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/predict_data/edit.html.erb
<h1>Editing Predict Datum</h1>

<%= render 'form', predict_datum: @predict_datum %>

<%= link_to 'Show', @predict_datum %> |
<%= link_to 'Back', predict_data_path %>

app/views/predict_data/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>
        <%= link_to "画像名", sort: "image_name DESC" %>
      </th>
      <th>
        <%= link_to "きれいな空", sort: "beautiful_sky DESC" %>
      </th>
      <th>
        <%= link_to "Notきれいな空", sort: "not_beautiful_sky DESC" %>
      </th>
      <th>
        <%= link_to "その他", sort: "other" %>
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @predict_data.each do |predict_datum| %>
      <tr>
        <td><img src ="http://pbl2-ranking.s3-website-ap-northeast-1.amazonaws.com/<%= predict_datum.image_name %>" width="64px" height="64px"></td>
        <td><%= predict_datum.beautiful_sky %></td>
        <td><%= predict_datum.not_beautiful_sky %></td>
        <td><%= predict_datum.other %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate(@predict_data) %>

<br>
<%= form_tag({controller: "predict_data", action: "import", method: "post"}, {multipart: true}) do %>
  <%= file_field_tag :file %>
  <%= submit_tag "オブジェクトを一括インポート" %>
<% end %>

app/views/predict_data/new.html.erb
<h1>New Predict Datum</h1>

<%= render 'form', predict_datum: @predict_datum %>

<%= link_to 'Back', predict_data_path %>

app/views/predict_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image name:</strong>
  <%= @predict_datum.image_name %>
</p>

<p>
  <strong>Beautiful sky:</strong>
  <%= @predict_datum.beautiful_sky %>
</p>

<p>
  <strong>Not beautiful sky:</strong>
  <%= @predict_datum.not_beautiful_sky %>
</p>

<p>
  <strong>Other:</strong>
  <%= @predict_datum.other %>
</p>

<%= link_to 'Edit', edit_predict_datum_path(@predict_datum) %> |
<%= link_to 'Back', predict_data_path %>